### ISSUE TITLE
alert handshake failure

### ISSUE THREAD

**Issue by vitriolix** [0x27/clypdown#2]
$ clypdown.py https://clyp.it/2akno5zg
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
{-} Something has gone horribly wrong! Please report on the github issue tracker with the following backtrace: 
[Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Traceback (most recent call last):
  File "/home/josh/bin/clypdown.py", line 45, in <module>
    main(args=sys.argv)
  File "/home/josh/bin/clypdown.py", line 41, in main
    song_title, mp3_url = get_mp3_url(url=args[1])
  File "/home/josh/bin/clypdown.py", line 29, in get_mp3_url
    fucking_json = json.loads(r.text)
UnboundLocalError: local variable 'r' referenced before assignment

**Comment by Iron-Wolf** [comment]
This repo seems to not being maintained by it's owner.
We maybe need to fork it, to at least have a functional project.

By the way, I found a workaround for this issue : 
just replace all `https` by `http` in the **get_mp3_url** method.
It's ugly but at least the script is able to download some file :)

**Comment by 0x27** [comment]
I should put up a notice, that this script is deprecated as the far better supported [youtube-dl](https://github.com/rg3/youtube-dl) project [added clyp.it support in 2015.](https://github.com/rg3/youtube-dl/issues/7134).
